id: P004163
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 10:57:30.876978
source_metadata:
  id: bdr:W1KG1610
  title: དགའ་ལྡན་ཆོས་འབྱུང་བཻ་ཌཱུ་རྱ་སེར་པོ།
  author: ''
  volumes:
    e4e21b3dd14d430d8aa86ae8b94761e5:
      image_group_id: I1KG1704
      title: ''
      volume_number: 1
      total_pages: 203
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
