id: I0ACAF00C
legacy_id: P004163
ocr_import_info:
  bdrc_scan_id: W1KG1610
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T09:23:41'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T08:28:13.105910+00:00'
last_modified: 2022-08-31 16:28:20.852362
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG1610
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG1610
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དགའ་ལྡན་ཆོས་འབྱུང་བཻ་ཌཱུ་རྱ་སེར་པོ།
  author: སྡེ་སྲིད་སངས་རྒྱས་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.5482899521266391
  ocr_word_median_confidence_index: 0.5400000214576721
quality: null
bases:
  I1KG1704:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG1704
      total_pages: 203
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG1704.txt
    statistics:
      ocr_word_median_confidence_index: 0.5400000214576721
      ocr_word_mean_confidence_index: 0.5482899521266391
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
